import { waitUntil } from "@vercel/functions";
import { store } from "../repositories/index.js";
import { ai } from "./ai/index.js";
import { storage } from "./storage.js";
import { calculatePki } from "./pki.js";

class JobService {
  async enqueue(input:Parameters<typeof store.createJob>[0]){const job=await store.createJob(input); this.defer(this.process(job.id)); return job;}
  defer(promise:Promise<unknown>){if(process.env.VERCEL){waitUntil(promise);}else{void promise.catch(()=>undefined);}}
  async process(id:string){const job=await store.claimJob(id);if(!job)return;try{if(job.type==="EVIDENCE_EXTRACT")await this.extract(job);else if(job.type==="PERSONA_REBUILD")await this.rebuild(job);else await store.completeJob(job.id,{skipped:true});}catch(error){const message=error instanceof Error?error.message:"작업 실패";const globalRebuild=job.type==="PERSONA_REBUILD"&&job.payload.ownerScope==="GLOBAL";await store.failJob(job.id,message,!globalRebuild);if(job.type==="EVIDENCE_EXTRACT"&&job.payload.ownerScope==="GLOBAL")await store.updateGlobalEvidence(job.payload.evidenceId,{status:"FAILED",errorMessage:message}).catch(()=>undefined);else if(job.type==="EVIDENCE_EXTRACT"&&job.sessionId)await store.updateEvidence(job.sessionId,job.payload.evidenceId,{status:"FAILED",errorMessage:message}).catch(()=>undefined);if(globalRebuild)void store.recordAdminOperation("GLOBAL_PERSONA_REBUILD","FAILED",{error:"operation_failed"}).catch(()=>undefined);else if(job.type==="PERSONA_REBUILD"&&job.sessionId&&job.bossId)await store.setBossStatus(job.sessionId,job.bossId,"FAILED",message);}}
  async extract(job:any){const global=job.payload.ownerScope==="GLOBAL";const evidence=global?await store.getGlobalEvidence(job.payload.evidenceId):await store.getEvidence(job.sessionId,job.payload.evidenceId);if(!evidence)throw new Error("근거를 찾을 수 없습니다.");if(global)await store.updateGlobalEvidence(evidence.id,{status:"PROCESSING",errorMessage:null});else await store.updateEvidence(job.sessionId,evidence.id,{status:"PROCESSING",errorMessage:null});let content=evidence.rawText??"";if(evidence.storagePath){content=evidence.type==="TXT"?await storage.downloadText(evidence.storagePath):`이미지 URL: ${await storage.createSignedDownload(evidence.storagePath)}`;}const parsed=await ai.extractEvidence({content,kind:evidence.type});if(global)await store.updateGlobalEvidence(evidence.id,{status:"READY",parsedData:parsed,errorMessage:null});else await store.updateEvidence(job.sessionId,evidence.id,{status:"READY",parsedData:parsed,errorMessage:null});await store.completeJob(job.id,{evidenceId:evidence.id,observations:parsed.observations.length});}
  async rebuild(job:any){if(job.payload.ownerScope==="GLOBAL"){const [boss,evidence,survey]=await Promise.all([store.getGlobalBoss(),store.listGlobalEvidence(),store.listGlobalSurveyAnswers()]);const ready=evidence.filter(item=>item.status==="READY");const persona=await ai.buildPersona({profile:null,boss,evidence:ready,survey});const pki=calculatePki(ready,persona);await store.setGlobalBossPersona(persona,pki);await store.completeJob(job.id,{bossId:boss.id,pki});void store.recordAdminOperation("GLOBAL_PERSONA_REBUILD","SUCCEEDED",{bossId:boss.id,evidence:ready.length}).catch(()=>undefined);return;}const boss=await store.getBoss(job.sessionId,job.bossId);if(!boss||boss.scope==="GLOBAL")throw new Error("상사를 찾을 수 없습니다.");await store.setBossStatus(job.sessionId,job.bossId,"BUILDING");const [profile,evidence,survey]=await Promise.all([store.getProfile(job.sessionId),store.listEvidence(job.sessionId,job.bossId),store.listSurveyAnswers(job.sessionId,job.bossId)]);const persona=await ai.buildPersona({profile,boss,evidence,survey});const pki=calculatePki(evidence,persona);await store.setBossPersona(job.sessionId,job.bossId,persona,pki);await store.completeJob(job.id,{bossId:boss.id,pki});}
  async runPending(limit=5){const jobs=await store.listRunnableJobs(limit);for(const job of jobs)await this.process(job.id);return jobs.length;}
}
export const jobs=new JobService();
