import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { evidenceSchema, MAX_IMAGE_EVIDENCE_PER_BOSS } from "../shared.js";
import { store } from "../repositories/index.js";
import { requireSession, sessionExpiry } from "../services/session.js";
import { jobs } from "../services/jobs.js";
import { HttpError } from "../utils/http.js";
import { parse } from "../utils/validation.js";
import { storage } from "../services/storage.js";
export const evidenceRoutes:FastifyPluginAsync=async(app)=>{
  app.get("/bosses/:bossId/evidence",async(request)=>{const s=await requireSession(request);const bossId=(request.params as any).bossId;if(!(await store.getBoss(s.id,bossId)))throw new HttpError(404,"상사를 찾을 수 없습니다.");return {evidence:await store.listEvidence(s.id,bossId)};});
  app.post("/bosses/:bossId/evidence",{config:{rateLimit:{max:20,timeWindow:"1 minute"}}},async(request,reply)=>{const s=await requireSession(request);const bossId=(request.params as any).bossId;const boss=await store.getBoss(s.id,bossId);if(!boss||boss.scope==="GLOBAL")throw new HttpError(404,"상사를 찾을 수 없습니다.");const body=parse(evidenceSchema,request.body);let storagePath:string|null=null;let sourceName:string|null=body.type==="TEXT"?"붙여넣기":null;let type:string=body.type;if(body.type!=="TEXT"){const intent=await store.getUploadIntent(s.id,body.uploadIntentId);if(!intent||intent.bossId!==bossId||intent.completedAt)throw new HttpError(400,"유효하지 않은 업로드입니다.");if(!(await storage.verify(intent.storagePath,intent.sizeBytes,intent.contentType)))throw new HttpError(400,"업로드된 파일을 확인할 수 없습니다.","UPLOAD_MISMATCH");storagePath=intent.storagePath;sourceName=intent.originalName;type=intent.contentType==="text/plain"?"TXT":"IMAGE";await store.completeUploadIntent(s.id,intent.id);}const input={bossId,sessionId:s.id,type,status:"PENDING",sourceName,rawText:body.type==="TEXT"?body.rawText:null,storagePath,parsedData:null,observedAt:null,expiresAt:sessionExpiry()};const evidence=type==="IMAGE"?await store.createImageEvidenceWithLimit(input,MAX_IMAGE_EVIDENCE_PER_BOSS):await store.createEvidence(input);if(!evidence){if(storagePath)await storage.remove([storagePath]);throw new HttpError(409,`이미지는 상사별로 최대 ${MAX_IMAGE_EVIDENCE_PER_BOSS}장까지 등록할 수 있습니다.`,"IMAGE_LIMIT_EXCEEDED");}const job=await jobs.enqueue({sessionId:s.id,bossId,type:"EVIDENCE_EXTRACT",payload:{evidenceId:evidence.id}});return reply.code(202).send({evidence,jobId:job.id});});
  app.delete("/bosses/:bossId/evidence/:evidenceId",async(request)=>{const s=await requireSession(request);const {bossId,evidenceId}=parse(z.object({bossId:z.string().uuid(),evidenceId:z.string().uuid()}),request.params);const boss=await store.getBoss(s.id,bossId);if(!boss||boss.scope!=="SESSION")throw new HttpError(404,"상사를 찾을 수 없습니다.","BOSS_NOT_FOUND");const evidence=await store.getEvidence(s.id,evidenceId);if(!evidence||evidence.bossId!==bossId)throw new HttpError(404,"이미지 자료를 찾을 수 없습니다.","EVIDENCE_NOT_FOUND");if(evidence.type!=="IMAGE")throw new HttpError(400,"이미지 자료만 삭제할 수 있습니다.","IMAGE_EVIDENCE_REQUIRED");if(evidence.storagePath)await storage.remove([evidence.storagePath]);const deleted=await store.deleteImageEvidenceWithJobs(s.id,bossId,evidenceId);if(!deleted)throw new HttpError(404,"이미지 자료를 찾을 수 없습니다.","EVIDENCE_NOT_FOUND");return {deletedEvidenceId:evidenceId,deletedJobIds:deleted.jobIds};});
};
