import { useQuery } from "@tanstack/react-query";
import { Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { Wordcloud } from "@visx/wordcloud";
import { Text } from "@visx/text";
import { api } from "../../services/api-client";
interface Dashboard{includesDemo:boolean;overview:{totalUses:number;activeSubjects:number;topFeature:string;summary:string};topics:{text:string;value:number}[];rankGap:{label:string;value:number}[];ageGap:{label:string;value:number}[];byTime:{label:string;value:number}[]}
const featureLabel=(feature:string)=>({TRANSLATE:"번역",CHAT:"대화",SIMULATE:"시뮬레이션",MONOLOGUE:"혼잣말",PERSONA_REBUILD:"페르소나 재생성"}[feature]??feature);
export function HrDashboard(){const query=useQuery({queryKey:["hr-dashboard"],queryFn:()=>api<Dashboard>("/hr/dashboard")});if(query.isLoading)return <div className="loading-state"><div className="spinner"/></div>;if(!query.data)return <div className="empty-state">집계 데이터를 불러오지 못했습니다.</div>;const d=query.data;return <main className="hr-main"><header className="hr-title-row"><div><h2>조직 커뮤니케이션 인사이트</h2><p className="hint">익명화된 집계이며 5명 미만의 소표본 구간도 포함합니다.</p></div>{d.includesDemo&&<span className="demo-badge">데모 데이터 포함</span>}</header><p className="hr-summary">{d.overview.summary}</p><div className="metric-line"><div><strong>{d.overview.totalUses.toLocaleString()}</strong><span>AI 기능 사용</span></div><div><strong>{d.overview.activeSubjects}</strong><span>익명 사용자</span></div><div><strong>{featureLabel(d.overview.topFeature)}</strong><span>가장 많이 쓴 기능</span></div></div><section id="topics" className="chart-section"><h3>자주 등장한 주제</h3><TopicCloud words={d.topics}/></section><div className="chart-grid"><Chart title="직급 차이별 사용량" data={d.rankGap}/><Chart title="나이 차이별 사용량" data={d.ageGap}/></div><section id="time" className="chart-section"><h3>24시간 사용 흐름</h3><ResponsiveContainer width="100%" height={280}><LineChart data={d.byTime}><CartesianGrid stroke="rgba(38,58,69,.1)" vertical={false}/><XAxis dataKey="label" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip/><Line type="monotone" dataKey="value" stroke="#4E8D7C" strokeWidth={2} dot={d.byTime.filter(item=>item.value>0).length<=1}/></LineChart></ResponsiveContainer></section></main>}
function TopicCloud({words}:{words:{text:string;value:number}[]}){return <div className="word-cloud"><svg viewBox="0 0 720 240" role="img" aria-label="주요 대화 주제 워드 클라우드"><Wordcloud words={words} width={720} height={240} font="Pretendard, sans-serif" fontSize={(word)=>Math.max(16,Math.min(46,word.value/2))} padding={5} spiral="archimedean" rotate={()=>0} random={()=>.5}>{cloudWords=>cloudWords.map(word=><Text key={word.text} fill="#35576B" textAnchor="middle" transform={`translate(${word.x}, ${word.y}) rotate(${word.rotate})`} fontSize={word.size} fontFamily={word.font}>{word.text}</Text>)}</Wordcloud></svg></div>}
function Chart({title,data}:{title:string;data:{label:string;value:number}[]}){return <section className="chart-section"><h3>{title}</h3><ResponsiveContainer width="100%" height={260}><BarChart data={data}><CartesianGrid stroke="rgba(38,58,69,.1)" vertical={false}/><XAxis dataKey="label" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip/><Bar dataKey="value" fill="#35576B" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></section>}
