import { describe,expect,it,vi } from "vitest";
import type { BossPersona, LegacyBossPersona } from "@askboss/shared";
import { calculatePki, PKI_FRESHNESS_DECAY_DAYS } from "../src/services/pki";

const persona:BossPersona={summary:"",uncertainty:[],traits:[]};
const categories=["업무 지시","보고 및 피드백","일정 관리","의사결정","일상 소통"];
const evidenceAtAge=(days:number)=>categories.map((category,index)=>{const observedAt=new Date(Date.now()-days*86_400_000).toISOString();return {id:`age-${days}-${index}`,bossId:"b",sessionId:"s",type:"TEXT",status:"READY",rawText:"x",storagePath:null,parsedData:{observations:[{category,contextQuality:1,observedAt}]},observedAt,createdAt:observedAt,expiresAt:"2030-01-01T00:00:00Z"};});
describe("calculatePki",()=>{
  it("returns zero without evidence or traits",()=>{expect(calculatePki([],persona)).toEqual({completeness:0,evidenceReliability:0,diversity:0,freshness:0,score:0});});
  it("caps every component and computes deterministically",()=>{vi.setSystemTime(new Date("2026-01-15T00:00:00Z"));const categories=["업무 지시","보고 및 피드백","일정 관리","의사결정","일상 소통"];const evidence=categories.map((category,index)=>({id:`e${index}`,bossId:"b",sessionId:"s",type:"TEXT",status:"READY",rawText:"x",storagePath:null,parsedData:{observations:[{category,contextQuality:1,observedAt:"2026-01-15T00:00:00Z"}]},observedAt:"2026-01-15T00:00:00Z",createdAt:"2026-01-15T00:00:00Z",expiresAt:"2026-01-16T00:00:00Z"}));const result=calculatePki(evidence as any,{...persona,traits:[{category:"보고",key:"t",label:"t",value:"high",confidence:1,evidenceIds:["e0","e1","e2"]}]});expect(result.completeness).toBe(20);expect(result.evidenceReliability).toBe(100);expect(result.freshness).toBe(100);expect(result.score).toBeGreaterThanOrEqual(64);expect(result.score).toBeLessThanOrEqual(65);vi.useRealTimers();});
  it("keeps calculating PKI for legacy stored personas",()=>{const legacy:LegacyBossPersona={summary:"legacy",communication:{tone:"",messageLength:"",directness:50,formality:50},reporting:{preferredLength:"",preferredStructure:[],frequentChecks:[]},decisionMaking:{speed:"",riskTolerance:"",autonomyPreference:""},management:{hierarchyPreference:"",feedbackStyle:"",deadlineSensitivity:""},recurringPatterns:[],recurringPhrases:[],humorStyle:null,uncertainty:[],traits:[{key:"legacy",label:"기존 특성",value:"높음",confidence:0.8,evidenceIds:[]}]};expect(calculatePki([],legacy)).toEqual({completeness:0,evidenceReliability:0,diversity:0,freshness:0,score:0});});
  it.each([[0,100],[180,78],[365,61],[730,37]])("uses a two-year freshness decay at %i days",(days,expected)=>{vi.setSystemTime(new Date("2026-09-20T00:00:00Z"));expect(PKI_FRESHNESS_DECAY_DAYS).toBe(730);expect(calculatePki(evidenceAtAge(days) as any,persona).freshness).toBe(expected);vi.useRealTimers();});
});
